feat: controllers-films-users 08
Indiannka/java-filmorate pull request #1
Opened 2022-06-07 21:46 UTC by Indiannka

ТЗ 8 спринта, проект Filmorate, добавлена модель и веб-контроллеры

2022-06-08 10:04 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
нужно отформатировать отступы

2022-06-08 10:05 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/AbstractController.java
> +abstract class AbstractController<T> {
для контроллеров абстрактные классы и интерфейсы не нужно делать

2022-06-08 10:06 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
можно добавить аннотацию ломбока `@Sl4j`, он сам добавит логгер в класс, а эту строчку можно убрать

2022-06-08 10:08 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        film.setId(FilmIdGenerator.generateId());
FilmGenerator лучше сделать сервисом (спринговая аннотация @Service) и использовать генератор как бин

это сильно упростит тестирование в будущем

2022-06-08 10:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        for (Film f : films.values()) {
можно заменить на `films.values().contains(film) `

2022-06-08 10:10 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final HashMap<Integer, User> users = new HashMap<>();
тип поля должен быть Map, а не класс-реализация HashMap

2022-06-08 10:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CustomExceptionHandler.java
> +import java.util.List;
нужна пустая строка

2022-06-08 10:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CustomExceptionHandler.java
> +    @ExceptionHandler(Exception.class)
стоит разделить пустой строкой

2022-06-08 10:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorResponse.java
> +import java.util.List;
нужно разделить пустой строкой

2022-06-08 10:12 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@EqualsAndHashCode
эти аннотации можно заменить одной @Data

2022-06-08 10:12 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
пустая строка не нужна после аннотаций

2022-06-08 10:16 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @EqualsAndHashCode.Exclude
правильно ли, что фильмы с разными id будут одинаковые по equals и метод isExist будет отдавать true?

обычно, для модели не переопределяют equals, потому что это может привести к неочевидным результатам сравнения

а одинаковость двух объектов сравнивают по уникальному идентификатору - у этого класса это как раз id

2022-06-08 10:17 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(max = 200, message = "Описание не должно превышать 200 символов")
стоит сделать публичную константу MAX_DESCRIPTION_LENGTH, и ее можно использовать в тестах как expected значение

2022-06-08 10:18 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmIdGenerator.java
> +    public static synchronized int generateId() {
нужно разделить пустой строкой

2022-06-08 10:18 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmIdGenerator.java
> +    private FilmIdGenerator(){}
конструктор идет после полей

если сделать класс - спринг бином, то он по-умолчанию будет синглтоном

2022-06-08 10:19 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
нужно заменить на @Data и убрать пустою строку

2022-06-08 10:19 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
лишняя пустая строка

2022-06-08 10:20 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank (message = "Поле не должно быть пустым")
аннотации легче читаются, когда выставлены в порядке увеличения длины
плюс можно разделить поля пустыми строками

2022-06-08 10:21 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull @NotBlank (message = "Поле не должно быть пустым")
нужно соблюдать единый стиль для аннотаций: в других местах они идут одна над другой

2022-06-08 10:21 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/UserIdGenerator.java
> +    private static volatile int counter = 1;
такие же замечания, что и у другого генератора

2022-06-08 10:22 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/validators/ReleaseDate.java
> +    String message() default "{ReleaseDate.invalid.must be not earlier 1985-12-28}";
дата самого раннего релиза должна быть 1895

2022-06-08 10:22 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/validators/ReleaseDateValidator.java
> +        LocalDate releaseDate = LocalDate.of(1895, 12, 28);
нужно вынести в константу

2022-06-08 10:23 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	private Validator validator;
нужно поправить отсупы

2022-06-08 10:24 UTC, makholin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	private Film film = new Film();
данные для тестирования должны быть у каждого метода свои, общие на весь класс не нужно делать

это может привести к неочевидным падениям тестов

2022-06-08 10:26 UTC, makholin requested changes
Нужно исправить замечания и ко всему коду применить автоформатирование (ctrl alt L в идее)

2022-06-08 19:00 UTC, Indiannka commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        film.setId(FilmIdGenerator.generateId());
Я сделала с аннотацией по примеру из инета, но не уверена, что как надо.

2022-06-08 19:30 UTC, Indiannka commented
Запушила изменения через второй коммит, это правильно?)

2022-06-09 22:05 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    IdGenerator filmIdGenerator;
поля должны быть private

2022-06-09 22:11 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/service/IdGenerator.java
> +    private volatile int filmCounter = 1;
это решение норм

просто расскажу, как можно сделать по другому:
по-умолчанию спринг создает один объект каждого сервиса и везде, где сервис используется, он подсовывает этот объект

но можно создавать несколько бинов одного класса и они будут подсовываться в разные места разные:
то есть можно сделать  2 бина `IdGenerator filmIdGenerator` и `IdGenerator userIdGenerator` и с помощью аннотации @Qualifier выбирать, какой из бинов подставить в поле

2022-06-09 22:13 UTC, makholin approved these changes
Работа принята

2022-06-12 10:09 UTC, merged