feat: add-friends-likes 09
Indiannka/java-filmorate pull request #2
Opened 2022-06-21 22:23 UTC by Indiannka

2022-06-23 08:03 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final Storage<Film> storage;
переменную лучше назвать filmStorage, потому что в будущем может быть несколько стораджей в классе

2022-06-23 08:05 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CustomExceptionHandler.java
> +    protected @NonNull ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex,
точно тут нужна NonNull аннотация?

2022-06-23 08:07 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/BaseEntity.java
> +public class BaseEntity {
этот класс не содержит каких-то специфичных для всех entity методов, поэтому наследование от него ничего не дает, на данный момент можно убрать

2022-06-23 08:12 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@EqualsAndHashCode(of = {"id", "name", "description", "releaseDate", "duration"}, callSuper = false)
лучше оставить дефолтную имплементацию для объекта, которая сравнивает ссылки
иначе это может сломать где-нибудь логику, которая использует equals

если в бизнес логике сравнивать фильмы, то стоит определиться, какие фильмы одинаковые:
если у фильма одинаковые ид, то это один и тот же фильм?
или фильм один и тот же, если еще и имя, описание и тд одинаковые

обычно делают так, что если у объектов один и тот же ид, то это объекты для одной и той же сущности
а для сравнения всех полей можно сделать еще один метод

2022-06-23 08:14 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
пустая строка между аннотациями и объявлениями классов и методов не нужна

2022-06-23 08:27 UTC, makholin requested changes
Хорошо реализована структура стораджей 

Нужно исправить замечания

2022-06-23 20:53 UTC, Indiannka commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CustomExceptionHandler.java
> +    protected @NonNull ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException ex,
я следовала подсказкам анализатора кода)

2022-06-23 20:54 UTC, Indiannka commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@EqualsAndHashCode(of = {"id", "name", "description", "releaseDate", "duration"}, callSuper = false)
Вернула callSuper, а у пользователя исключила список друзей, чтобы избежать ошибки StackOverFLow Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate ru.yandex.practicum.filmorate.model.User.toString().

Вроде  в ошибке проблема в toString, но по факту из-за дефолтного equals падало в методе 
private void addFriend(User user, User friend) {
        user.getFriends().add(friend);
        friend.getFriends().add(user); //после этой строки
    }
Я догадываюсь это из-за перекрестных ссылок, но как оно там конфликтует не до конца понимаю.
Не знаю, как по другому обойти, хранить id в Set как по заданию или оставить

2022-06-25 08:35 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@EqualsAndHashCode(of = {"id", "name", "description", "releaseDate", "duration"}, callSuper = false)
нужно хранить не целого юзера в сете, а только их id
тогда все будет работать)

2022-06-25 08:36 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/CustomExceptionHandler.java
> +    public final ResponseEntity handleAllExceptions(Exception ex, WebRequest request) {
параметризация то норм была, просто надо было не самым верхнеуровневым Object параметризовывать, а создать какой-нибудь класс для представления ошибок ErrorResponse и параметризовать им

2022-06-25 08:38 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @EqualsAndHashCode.Exclude
нужно сделать хранение только id в сете, тогда все эти аннотации будут не нужны

по ид доставать юзеров нужно будет также через `userService.getById(id);`

2022-06-25 08:39 UTC, makholin requested changes
Нужно исправить замечание, и упростить equals методы у классов, исправив хранение друзей

2022-06-27 22:20 UTC, makholin approved these changes
Работа принята

2022-06-28 09:23 UTC, merged